# This workflow seeds translations by calling the configured seed translations endpoint with
# a source strings file and translations string file for each application and language code
# combination.

name: Seed Translations

on:
  workflow_dispatch:
    inputs:
      application_name:
        description: 'Application to seed translations for. Leave blank to run all.'
        required: false
        type: string
      translation_language:
        description: 'Language code to seed translations for in Google translations format (i.e. ISO 639-1 format), typically {language-code}{-region-code (optional)} (e.g. es-419 or pt-PT). Leave blank to run all.'
        required: false
        type: string

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      applications: ${{ steps.generate_repo_matrix.outputs.applications }}
      translation_languages: ${{ steps.generate_repo_matrix.outputs.translation_languages }}
    steps:
      - uses: actions/github-script@v7
        id: generate_repo_matrix
        with:
          script: |
            const allJavascriptApps = [
              'frontend-app-account',
              'frontend-app-admin-portal',
              'frontend-app-authn',
              'frontend-app-authoring',
              'frontend-app-communications',
              'frontend-app-discussions',
              'frontend-app-enterprise-api-doc',
              'frontend-app-enterprise-checkout',
              'frontend-app-enterprise-public-catalog',
              'frontend-app-gradebook',
              'frontend-app-learner-dashboard',
              'frontend-app-learner-portal-enterprise',
              'frontend-app-learner-portal-programs',
              'frontend-app-learner-record',
              'frontend-app-learning',
              'frontend-app-ora',
              'frontend-app-ora-grading',
              'frontend-app-payment',
              'frontend-app-profile',
              'frontend-app-program-console',
              'frontend-app-publisher',
              'frontend-app-skills',
              'frontend-app-support-tools',
              'frontend-component-authn-edx',
              'frontend-component-footer-edx',
              'frontend-component-header-edx',
              'frontend-components-tinymce-advanced-plugins-edx',
              'frontend-plugin-advertisements',
              'frontend-plugin-authn',
              'frontend-plugin-learner-dashboard',
              'frontend-plugin-notifications',
              'frontend-plugin-persona',
              'frontend-plugin-recommendations',
              'frontend-platform',
              'paragon',
              'studio-frontend',
              'frontend-plugin-framework',
            ];

            // The seed translations endpoint supports language codes that follow the IETF BCP 47 standard.
            // These language codes are a combination of a two-letter language code (i.e. the ISO 639-1 standard) and the country code (i.e. the ISO 3166-1 alpha-2 standard), separated by a hyphen.
            // As an example, "it-it".
            // However, the filenames in this repository for JSON messages file use IETF BCP 47 language codes with underscores instead of hyphens. This is not uncommon.
            // Note that the language codes used in JSON messages files come from formatjs during the messages extraction process, which is implemented by scripts in frontend-build.
            // As a result, we maintain a map between language codes expected by the seed translations endpoint and the language codes used for JSON messages filenames in this repository.
            
            // Leave a comment about this fa-ir missing file and whether to assume underscore.
            const languages = [
              { edxLang: "ar", repoLang: "ar" },
              { edxLang: "ca", repoLang: "ca" },
              { edxLang: "da", repoLang: "da" },
              { edxLang: "de-de", repoLang: "de_DE" },
              { edxLang: "el", repoLang: "el" },
              { edxLang: "en", repoLang: "en" },
              { edxLang: "es-419", repoLang: "es_419" },
              { edxLang: "es-es", repoLang: "es_ES" },
              { edxLang: "fa", repoLang: "fa" },
              { edxLang: "fa-ir", repoLang: "fa-ir" },
              { edxLang: "fr", repoLang: "fr" },
              { edxLang: "fr-ca", repoLang: "fr_CA" },
              { edxLang: "he", repoLang: "he" },
              { edxLang: "hi", repoLang: "hi" },
              { edxLang: "id", repoLang: "id" },
              { edxLang: "it-it", repoLang: "it_IT" },
              { edxLang: "ko-kr", repoLang: "ko-kr" },
              { edxLang: "pl", repoLang: "pl" },
              { edxLang: "pt-br", repoLang: "pt_BR" },
              { edxLang: "pt-pt", repoLang: "pt_PT" },
              { edxLang: "ru", repoLang: "ru" },
              { edxLang: "sw", repoLang: "sw" },
              { edxLang: "te", repoLang: "te" },
              { edxLang: "th", repoLang: "th" },
              { edxLang: "tr-tr", repoLang: "tr_TR" },
              { edxLang: "uk", repoLang: "uk" },
              { edxLang: "zh-cn", repoLang: "zh-_CN" }
            ];

            const languageMap = new Map(languages.map(lang => [lang.edxLang, repoLang]));

            // Need to use a workaround until https://github.com/actions/toolkit/issues/1576 is fixed
            // const appInput = core.getInput('application_name');
            // const languageInput = core.getInput('translation_language');
            const appInput = ${{ toJSON(github.event.inputs.application_name) }} ?? '';
            const languageInput = ${{ toJSON(github.event.inputs.translation_language) }} ?? '';
            const selectedApp = appInput ? appInput.toLowerCase() : '';
            const selectedLanguage = languageInput ? languageInput.toLowerCase() : '';

            if (selectedApp !== '' && !allJavascriptApps.includes(selectedApp)) {
              core.setFailed(`Selected application ${selectedApp} is not a valid option.`);
              return;
            }
            if (selectedLanguage !== '' && !Objects.keys(languageMap).includes(selectedLanguage)) {
              core.setFailed(`Selected language ${selectedLanguage} is not a valid option.`);
              return;
            }

            const applications = selectedApp === '' ? allJavascriptApps : [selectedApp];
            const translation_languages = selectedLanguage === '' ? Object.values(languageMap) : languageMap[selectedLanguage];

            core.setOutput('applications', applications);
            core.setOutput('translation_languages', translation_languages);

  seed-translations:
    continue-on-error: true
    needs: setup-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        application: ${{ fromJson(needs.setup-matrix.outputs.applications) }}
        translation_language: ${{ fromJson(needs.setup-matrix.outputs.translation_languages) }}
    
    steps:
      - name: Clone ${{ github.repository }}
        uses: actions/checkout@v5
      
      # - name: Convert ${{ matrix.translation_language }} language code for ${{ matrix.application }} to expected format
      #   run: |
      #     # TODO: add better handling for language codes without region code
      #     language_code=$(echo ${{ matrix.translation_language }} | awk -F'-' '{print tolower($1) "_" toupper($2)}')
      #     echo "LANGUAGE_CODE=$language_code" >> $GITHUB_ENV

      # - name: Convert ${{ matrix.translation_language }} language code for ${{ matrix.application }} to expected format
      #   run: |
      #     language_code=${{ matrix.translation_language }}
      #     if [[ "$language_code" == *-* ]]; then
      #       # If the language code contains a hyphen, process it to the format language_REGION.
      #       language_code=$(echo $language_code | awk -F'-' '{print tolower($1) "_" toupper($2)}')
      #     else
      #       # If there's no hyphen, just convert to lowercase.
      #       language_code=$(echo $language_code | tr '[:upper:]' '[:lower:]')
      #     fi
      #     echo "LANGUAGE_CODE=$language_code" >> $GITHUB_ENV

      - name: Find ${{ matrix.translation_language.edxLang }} language translations files for ${{ matrix.application }}
        id: find-files
        run: |
          translations_file_path="translations/${{ matrix.application }}/src/i18n/messages/${{ matrix.translation_language.repoLang }}.json"
          if [ -f "$translations_file_path" ]; then
            echo "Translations file exists: $translations_file_path."
          else
            echo "Translations file does not exist: $translations_file_path. Skipping."
            exit 1
          fi

          source_strings_file_path="translations/${{ matrix.application }}/src/i18n/transifex_input.json"
          if [ -f "$source_strings_file_path" ]; then
            echo "Source strings file exists: $source_strings_file_path."
          else
            echo "Source strings file does not exist: $source_strings_file_path. Skipping."
            exit 1
          fi

          echo "TRANSLATIONS_FILE=$translations_file_path" >> $GITHUB_ENV
          echo "SOURCE_STRINGS_FILE=$source_strings_file_path" >> $GITHUB_ENV

      - name: Call seed translations endpoint for ${{ matrix.translation_language.edxLang }} language code for ${{ matrix.application}}
        id: seed-translations-json
        run: |
          status_code=$(curl -s -w "%{http_code}" -o /tmp/seed_translations_response.txt -X POST ${{ secrets.EDX_AI_TRANSLATIONS_API_ROOT }} \
            -F application_name=${{ matrix.application }} \
            -F translation_language=${{ matrix.translation_language.edxLang }} \
            -F source_language=en \
            -F translations_file=@"${{ env.TRANSLATIONS_FILE }}" \
            -F source_strings_file=@"${{ env.SOURCE_STRINGS_FILE }}")
          
          if [ "$status_code" -eq 200 ]; then
            echo "API call succeeded with status code $status_code."
          else
            echo "API call failed with status code $status_code."